const express = require("express");
const router = express.Router();
const adminDashboardController = require("../controllers/adminDashboardController");
const adminSupportController = require("../controllers/adminSupportController");
const analyticsController = require("../controllers/analyticsController");
const { uploadPackageImage, uploadBannerImage, uploadInvoicePdf } = require("../middleware/uploadMedia");
const { uploadChatFile } = require("../middleware/uploadChat");

router.get("/analytics/overview", analyticsController.getOverview);
router.get("/analytics/pr", analyticsController.getPr);
router.get("/analytics/users/summary", analyticsController.getUsersSummary);
router.get("/analytics/users/list", analyticsController.getUsersList);
router.get("/analytics/sales/summary", analyticsController.getSalesSummary);
router.get("/analytics/sales/packages", analyticsController.getSalesPackages);
router.get("/analytics/sales/customers", analyticsController.getSalesCustomers);
router.get("/analytics/sales/payments", analyticsController.getSalesPayments);
router.get("/analytics/sales/package-buyers", analyticsController.getSalesPackageBuyers);
router.get("/editorial-summary", adminDashboardController.getEditorialSummary);
router.get("/editorial-notifications", adminDashboardController.getEditorialNotifications);
router.post("/editorial-mark-viewed", adminDashboardController.postEditorialMarkViewed);
router.get("/gallery-images", adminDashboardController.getGalleryImages);
router.delete("/gallery-images/:id", adminDashboardController.deleteGalleryImage);
router.get("/editorial-press-releases/export.csv", adminDashboardController.exportEditorialPressReleasesCsv);
router.get("/editorial-press-releases", adminDashboardController.getEditorialPressReleases);
router.get("/press-release/create-data", adminDashboardController.getPressReleaseCreateData);
router.get("/press-release/gallery-detail/:id", adminDashboardController.getPressReleaseGalleryDetail);
router.post("/press-release/autofill-company", adminDashboardController.postPressReleaseAutofillCompany);
router.get("/press-release/check-title", adminDashboardController.getPressReleaseCheckTitle);
router.get("/press-release/:id/edit-data", adminDashboardController.getPressReleaseEditData);
router.get("/press-release/:id/view-data", adminDashboardController.getPressReleaseViewData);
router.get("/press-release/:id/status-history", adminDashboardController.getPressReleaseStatusHistory);
router.put("/press-release/:id", adminDashboardController.putPressReleaseUpdate);
router.put("/press-release/:id/after-published", adminDashboardController.putPressReleaseAfterPublished);
router.post("/press-release/preview-session", adminDashboardController.postPressReleasePreviewSession);
router.post("/press-release", adminDashboardController.postPressReleaseCreate);
router.delete("/press-release/:id/published", adminDashboardController.deletePressReleasePublished);
router.delete("/press-release/:id", adminDashboardController.deletePressRelease);
router.get("/login-logs", adminDashboardController.getLoginLogs);
router.get("/distributions", adminDashboardController.getDistributions);
router.get("/distributions/:id/history", adminDashboardController.getDistributionHistory);
router.get("/categories", adminDashboardController.getCategories);
router.post("/categories", adminDashboardController.createCategory);
router.put("/categories/:id", adminDashboardController.updateCategory);
router.patch("/categories/:id/status", adminDashboardController.updateCategoryStatus);
router.post("/categories/check-availability", adminDashboardController.checkCategoryAvailability);
router.get("/countries", adminDashboardController.getCountries);
router.post("/countries", adminDashboardController.createCountry);
router.put("/countries/:id", adminDashboardController.updateCountry);
router.patch("/countries/:id/status", adminDashboardController.updateCountryStatus);
router.delete("/countries/:id", adminDashboardController.deleteCountryPermanently);
router.get("/newsletters", adminDashboardController.getNewsletters);
router.get("/newsletters/export.csv", adminDashboardController.exportNewslettersCsv);
router.get("/newsletters/:id", adminDashboardController.getNewsletterById);
router.delete("/newsletters/:id", adminDashboardController.deleteNewsletterPermanently);
router.post("/newsletters/bulk-delete", adminDashboardController.deleteNewslettersBulk);
router.get("/payment-history/export.csv", adminDashboardController.exportPaymentHistoryCsv);
router.get("/invoices", adminDashboardController.getInvoices);
router.post("/invoices/upload", uploadInvoicePdf, adminDashboardController.uploadInvoice);
router.get("/invoices/:invId/download", adminDashboardController.downloadInvoice);
router.get("/payment-history", adminDashboardController.getPaymentHistory);
router.get("/payment-history/:id", adminDashboardController.getPaymentHistoryDetail);
router.get("/payment-methods", adminDashboardController.getPaymentMethods);
router.patch("/payment-methods/:id/status", adminDashboardController.updatePaymentMethodStatus);
router.get("/payment-methods/:id/coinbase-users", adminDashboardController.getCoinbaseUsers);
router.get("/payment-methods/:id/coinbase-user-ids", adminDashboardController.getCoinbaseUserIds);
router.post("/payment-methods/:id/coinbase-users", adminDashboardController.updateCoinbaseUsers);
router.get("/packages", adminDashboardController.getPackages);
router.get("/packages/meta", adminDashboardController.getPackageMeta);
router.post("/packages", uploadPackageImage, adminDashboardController.createPackage);
router.put("/packages/:id", uploadPackageImage, adminDashboardController.updatePackage);
router.patch("/packages/:id/status", adminDashboardController.updatePackageStatus);
router.get("/packages/pricing-sequencer", adminDashboardController.getPricingSequencer);
router.post("/packages/pricing-sequencer/save", adminDashboardController.savePricingSequencer);
router.post("/packages/pricing-sequencer/reset", adminDashboardController.resetPricingSequencer);
router.get("/packages/pricing-sequencer/preview", adminDashboardController.getPricingPreview);
router.get("/packages/pricing-banner", adminDashboardController.getPricingBanner);
router.post("/packages/pricing-banner", uploadBannerImage, adminDashboardController.updatePricingBanner);
router.post("/distributions", adminDashboardController.createDistribution);
router.put("/distributions/:id", adminDashboardController.updateDistribution);
router.patch("/distributions/:id/status", adminDashboardController.updateDistributionStatus);
router.post("/country-code", adminDashboardController.addCountryCode);
router.post("/profile/send-otp", adminDashboardController.sendProfileOtp);
router.post("/profile/update", adminDashboardController.updateProfile);
router.get("/invoice-companies", adminDashboardController.getInvoiceCompanies);
router.get("/invoice-companies/:id", adminDashboardController.getInvoiceCompanyById);
router.put("/invoice-companies/:id", adminDashboardController.updateInvoiceCompany);

router.get("/support/meta", adminSupportController.getMeta);
router.get("/support/notifications", adminSupportController.getNotifications);
router.get("/support/tickets", adminSupportController.listTickets);
router.get("/support/tickets/:id", adminSupportController.getTicket);
router.post("/support/tickets", adminSupportController.createTicket);
router.post("/support/tickets/:id/messages", uploadChatFile, adminSupportController.sendMessage);
router.post("/support/tickets/:id/resolve", adminSupportController.resolveTicket);
router.post("/support/tickets/:id/approve", adminSupportController.approveTicket);
router.post("/support/tickets/:id/decline", adminSupportController.declineTicket);

module.exports = router;
